import fs from 'node:fs';
import { load } from 'cheerio';
import { visualEdition } from './visual-edition.mjs';
import { siteHeader } from './navigation.mjs';
import { applySharedLearning } from './shared-learning.mjs';
import { sharedTrimester,contributors,learningConnections } from '../data/learning.mjs';
import { facts, sources, statuses, modules, threads, nodes, edges, comparisons, custody, questions, corrections } from '../data/editorial.mjs';
const registry=JSON.parse(fs.readFileSync('data/registry.json','utf8'));
const {people,records,bonus}=registry;
const fontVariants={
  'instrument-serif':[[400,'normal'],[400,'italic']],
  spectral:[[300,'normal'],[300,'italic'],[400,'normal'],[400,'italic'],[500,'normal'],[600,'normal']],
  'archivo-narrow':[[400,'normal'],[500,'normal'],[600,'normal'],[700,'normal']],
};
fs.mkdirSync('assets/fonts',{recursive:true});
const fontCSS=[];
for(const [family,variants] of Object.entries(fontVariants)){
  const name=family.split('-').map(s=>s[0].toUpperCase()+s.slice(1)).join(' ');
  for(const [weight,style] of variants){
    const file=`${family}-latin-${weight}-${style}.woff2`;
    fs.copyFileSync(`node_modules/@fontsource/${family}/files/${file}`,`assets/fonts/${file}`);
    fontCSS.push(`@font-face{font-family:'${name}';font-style:${style};font-weight:${weight};font-display:swap;src:url('fonts/${file}') format('woff2')}`);
  }
  fs.copyFileSync(`node_modules/@fontsource/${family}/LICENSE`,`assets/fonts/${family}-LICENSE.txt`);
}
fs.writeFileSync('assets/fonts.css',fontCSS.join('\n')+'\n');
if(records.length!==facts.registered || records.length+bonus.length!==facts.total)throw new Error('Collection totals disagree');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>fs.readFileSync(`node_modules/lucide-static/icons/${name}.svg`,'utf8').replace(/<svg /,'<svg aria-hidden="true" focusable="false" ');
const source=id=>sources.find(s=>s.id===id);
const refs=ids=>`<div class="refs">${ids.map(id=>`<a href="${source(id).url}">${esc(source(id).title)} ${icon('arrow-up-right')}</a>`).join('')}</div>`;
const nav=page=>siteHeader(page,icon);
const footer=`<footer class="site-footer"><a class="footer-brand" href="index.html">MUFU <span>Museo del Futuro</span></a><p>Isthmus · Cohorte 2026<br>Edificio 106 · Ciudad del Saber, Panamá</p><p><a href="infografias.html">Infografías visuales</a><br>51 registros + 2 bonus = 53 objetos<br><a href="archivo.html#metodo">Fuentes, límites y correcciones</a></p><a href="#top">Volver arriba ${icon('arrow-up')}</a></footer>`;
const head=(title,path)=>`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#E4E6E1"><title>${title} · MUFU</title><meta name="description" content="${title}. Diez semanas, 53 objetos y una cita en 2047. Archivo, conexiones y fuentes del Museo del Futuro de Isthmus."><link rel="canonical" href="https://mufu.today/${path}"><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/archive.css"></head>`;
const shell=(title,path,page,body)=>head(title,path)+`<body class="archive-site" data-page="${page}" id="top"><a class="skip-link" href="#main">Saltar al contenido</a>${nav(path)}<main id="main">${body}</main>${footer}<script type="module" src="assets/experience.js"></script></body></html>`;
const label=(k,t)=>`<p class="section-label"><span>${k}</span>${t}</p>`;
const intro=(num,title,copy)=>`<div class="section-head">${label(num,title)}<h2>${title}</h2><p>${copy}</p></div>`;

const atlas=`
<section class="atlas-intro content-wide">
  ${label('Atlas / 01','Diez semanas. Una misma pregunta.')}
  <div class="intro-title"><h1>Todo estaba<br><em>conectado.</em></h1><p>Un carrete de fotos. Una voz en el espacio. Un reflejo sobre vidrio. Una pared.<br><strong>¿Quién decide qué merece ser recordado?</strong></p></div>
  <nav class="chapter-nav" aria-label="Capítulos del atlas"><a href="#conexiones">01 / El hilo</a><a href="#aprendizaje">02 / El trimestre</a><a href="#tiempo">03 / La espera</a><a href="#futuros">04 / Dos futuros</a><a href="#aparicion">05 / La luz</a></nav>
</section>
<section class="network-section" id="conexiones" aria-labelledby="network-title">
  <div class="content-wide"><div class="network-top"><div><p class="section-label">Lectura curatorial · relaciones conceptuales</p><h2 id="network-title">El hilo que une todo</h2></div><div class="thread-controls" role="group" aria-label="Hilo del atlas"><button type="button" data-thread="all" aria-pressed="true">Todos</button>${threads.map(t=>`<button type="button" data-thread="${t.id}" aria-pressed="false"><i style="--thread:${t.color}" aria-hidden="true"></i>${t.name}</button>`).join('')}</div></div>
    <p class="thread-description" id="thread-description">Memoria, representación, poder y tiempo atraviesan el mismo objeto.</p>
    <div class="network-layout"><div class="network-board"><svg class="network-lines" aria-hidden="true"></svg><div class="network-nodes">${nodes.map((n,i)=>`<button class="network-node" type="button" id="n-${n.id}" data-node="${n.id}" aria-pressed="${i===0}"><span class="node-top">${icon(n.icon)}<span>${esc(n.date)}</span></span><strong>${esc(n.title)}</strong><span class="node-colors" aria-hidden="true">${n.threads.map(id=>`<i style="background:${threads.find(t=>t.id===id).color}"></i>`).join('')}</span></button>`).join('')}</div></div>
    <aside class="node-inspector" aria-live="polite" aria-atomic="true"><p class="section-label" id="node-date">${nodes[0].date}</p><h3 id="node-title">${nodes[0].title}</h3><p id="node-text">${nodes[0].text}</p><div id="node-refs">${refs(nodes[0].sources)}</div><h4>Se conecta con</h4><ul id="node-links"></ul></aside></div>
    <details class="text-alternative"><summary>Leer todas las conexiones ${icon('plus')}</summary><div class="edge-list">${edges.map(([a,b,t,why])=>`<article data-edge="${a}-${b}-${t}"><p class="section-label">${threads.find(x=>x.id===t).name}</p><h3>${nodes.find(x=>x.id===a).title} <span aria-hidden="true">→</span> ${nodes.find(x=>x.id===b).title}</h3><p>${why}</p>${refs([...new Set([...nodes.find(x=>x.id===a).sources,...nodes.find(x=>x.id===b).sources])])}</article>`).join('')}</div></details>
  </div>
</section>
<section class="content-wide learning-section" id="aprendizaje">${intro('02','Diez semanas para aprender a mirar','Ocho módulos en secuencia. Las duraciones de cada módulo no están documentadas; esta infografía no los asigna a semanas concretas.')}
  <div class="learning-summary"><div><b>10</b><span>semanas</span></div><div><b>8</b><span>módulos</span></div><div><b>12</b><span>estudiantes</span></div><div><b>2</b><span>futuros</span></div></div>
  <ol class="learning-route">${modules.map(m=>`<li id="modulo-${m.id}"><span class="module-number">${m.id}</span><div class="module-heading">${icon(m.icon)}<h3>${m.title}</h3><p>${m.teacher}</p></div><div class="module-body"><p class="module-lesson">${m.lesson}</p><p>${m.text}</p><div class="module-change"><span>${m.from}</span>${icon('arrow-right')}<strong>${m.to}</strong></div><details><summary>Lo que quedó abierto</summary><p>${m.question}</p></details><a class="text-link" href="index.html#modulo-original-${m.id}">Leer el módulo completo ${icon('arrow-up-right')}</a></div></li>`).join('')}</ol>
  <div class="memory-band"><p class="section-label">Una relación de origen</p><h3>Mnemosine <span>→</span> Musas <span>→</span> <em>mouseion</em> <span>→</span> museo</h3><p>El relato del curso parte de la mitología de la memoria y la casa de las Musas para plantear que recordar también permite crear.</p>${refs(['curso'])}</div>
  <div class="print-actions"><a href="infografia.html">${icon('file-image')} Infografía completa para imprimir</a><button type="button" data-print>${icon('printer')} Imprimir el atlas</button></div>
</section>
<section class="time-section" id="tiempo"><div class="content-wide">${intro('03','Una cita con tres relojes','La fecha de apertura enlaza una misión espacial, un ejercicio de memoria y dos mundos imaginados.')}
  <div class="seventy"><div><span>5 septiembre</span><b>1977</b><p>Voyager 1 sale de la Tierra<br>12:56 UTC · 07:56 Panamá</p></div><div class="year-bridge"><strong>70 años</strong><span>mismo día · mismo minuto local</span></div><div><span>5 septiembre</span><b>2047</b><p>Cita de apertura de MUFU<br>07:56 Panamá · UTC−5</p></div></div>
  <div class="time-lanes"><article><p class="section-label">El espejo del curso</p><div class="mirror"><b>2005</b><span>21 años</span><b>2026</b><span>21 años</span><b>2047</b></div><p>Mirar hacia atrás para elegir qué enviar hacia adelante. Son distancias entre años: el cierre y la cita no ocurren el mismo día del calendario.</p></article><article><p class="section-label">Un año para releer</p><div class="mirror small"><b>2046</b><span>+ 1 año</span><b>2047</b></div><p>Los escenarios se contrastan con un presente nuevo. La especulación plantea posibilidades; no se califica como una predicción científica.</p></article></div>
  <details class="text-alternative"><summary>Cómo se calculan las fechas ${icon('plus')}</summary><p>2047 − 1977 = 70. Panamá usa UTC−5: 12:56 UTC equivale a 07:56. La ficha técnica de NASA precisa 12:56:01 UT; la cita de MUFU está definida al minuto. La fecha registrada de cierre es 04.09.2026, sin hora exacta. El calendario indica que se puede abrir; el archivo necesitará un acta para afirmar que se abrió.</p>${refs(['nasa','curso','cierre'])}</details>
</div></section>
<section class="content-wide futures-section" id="futuros">${intro('04','Dos mundos. La misma ausencia.','Ficciones de los estudiantes, 2046. El tercer término es MUFU, construido en 2026. Las conexiones se proponen como lectura curatorial.')}
  <div class="future-portraits"><article><span class="section-label">Transformación / 2046</span><h3>A través<br>de los LNS</h3><p>Las comunidades poseen el relato.<br>Una empresa posee la infraestructura.</p></article><article><span class="section-label">Colapso / 2046</span><h3>Nodos<br>de Memoria</h3><p>La historia oficial borra.<br>Las copias protegen lo que sobrevive.</p></article><article><span class="section-label">Convergencia / 2026</span><h3>El original<br>queda fuera.</h3><p>En MUFU, una aparición permite ver.<br>La pared impide tocar.</p></article></div>
  <div class="table-scroll" tabindex="0" role="region" aria-label="Comparación de futuros y MUFU"><table class="comparison"><caption>Acceso, representación y poder</caption><thead><tr><th scope="col">Pregunta</th><th scope="col">Transformación</th><th scope="col">Colapso</th><th scope="col">MUFU</th></tr></thead><tbody>${comparisons.map(row=>`<tr>${row.map((v,i)=>i?`<td>${v}</td>`:`<th scope="row">${v}</th>`).join('')}</tr>`).join('')}</tbody></table></div>
  <p class="source-note">El curso rastreó señales del presente en siete categorías. Las fichas de esas señales no están anexadas al repositorio; el atlas no inventa noticias ni fuentes para completarlas.</p>${refs(['futuros','hilo'])}
</section>
<section class="optics-section" id="aparicion"><div class="content-wide">${intro('05','Quien maneja la luz.','Pepper hace visible la separación entre una cosa y su imagen. La luz cambia lo que vemos; el objeto de origen permanece.')}
  <div class="optics-layout"><figure class="optics-stage"><div class="optics-image"><img src="medios/aparicion.jpg" alt="Fotograma conservado del video de apariciones de MUFU" width="1280" height="720" loading="lazy" id="light-image"><span class="stage-label">Representación del efecto</span></div><figcaption>Simulación conceptual de visibilidad sobre un fotograma. No es una medición del aparato real.</figcaption></figure><div class="optics-control"><p class="section-label">Experimento / reflejo</p><h3>El objeto está.<br>Su aparición depende de alguien.</h3><label for="light">Luz sobre la imagen <output id="light-value" for="light">70 %</output></label><input type="range" id="light" min="0" max="100" value="70"><p id="light-description" aria-live="polite">La aparición es visible.</p><svg class="optics-diagram" viewBox="0 0 320 160" role="img" aria-label="Esquema óptico sin escala: luz, vidrio a 45 grados y observador"><path d="M30 105 H270 M140 130 L230 40" fill="none" stroke="currentColor"/><path d="M60 35 L190 80 L285 105" fill="none" stroke="#825b2b" stroke-dasharray="5 5"/><text x="22" y="27">luz</text><text x="225" y="38">vidrio · 45°</text><text x="219" y="130">observador</text><text x="15" y="155">Reflexión óptica · sin escala</text></svg><p>La representación de Leia en <em>Star Wars</em> es un holograma de ficción. Su vínculo con Pepper es conceptual: presencia sin el cuerpo original.</p>${refs(['pepper','leia'])}</div></div>
  <div class="closing-thesis"><p>La lámpara, los lentes, la censura, la pared.</p><h2>Quien controla la separación<br><em>controla el significado.</em></h2><a href="archivo.html#custodia">Quién cuida la espera ${icon('arrow-up-right')}</a></div>
</div></section>`;

const recordCard=r=>`<article class="object-card" data-id="${r.id}"><a href="${r.source}" class="object-photo"><img src="${r.image.src}" alt="${esc(r.title)} · fotografía de registro" width="${r.image.width}" height="${r.image.height}" loading="lazy" decoding="async"><span>${r.id}</span></a><div class="object-caption"><p>${esc(r.person)}</p><h2><a href="${r.source}">${esc(r.title)}</a></h2><p class="object-material">${esc(r.fields.Material||'Material no declarado')}</p><button type="button" class="detail-command" data-inspect="${r.id}">Abrir registro ${icon('arrow-up-right')}</button></div></article>`;
const bonusCard=b=>`<article class="object-card bonus-card" data-id="${b.id}"><div class="bonus-space">${icon('package-plus')}<span>${b.id}</span></div><div class="object-caption"><p>Bonus · sin registro</p><h2>${b.title}</h2><p>No hay título, fotografía ni autor documentados en el archivo público. Este número es un identificador editorial.</p><a href="archivo.html#conteo">Fuente del conteo ${icon('arrow-up-right')}</a></div></article>`;
const collection=`<section class="content-wide collection-intro">${label('Colección / 02','Los originales permanecen tras la pared')}<div class="intro-title"><h1>53 objetos.<br><em>51 rastros visibles.</em></h1><p>De dónde vinieron, de qué están hechos y por qué importaron.<br><strong>La fotografía conserva una apariencia. La ficha conserva una declaración.</strong></p></div><div class="count-equation"><span><b>51</b> registrados</span><i>+</i><span><b>2</b> bonus sin ficha</span><i>=</i><span><b>53</b> objetos</span><a href="archivo.html#conteo">Procedencia del conteo ${icon('arrow-up-right')}</a></div></section>
<section class="collection-surface"><div class="content-wide"><form class="collection-filters" id="collection-filters" role="search"><div class="search-field">${icon('search')}<label class="sr-only" for="search">Buscar en los registros</label><input type="search" id="search" name="q" placeholder="Objeto, material, origen, historia…" autocomplete="off"></div><label>Autor<select name="persona" id="person"><option value="">Todas las personas</option>${people.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>Registro<select id="record-status" name="estado"><option value="">Todos</option><option value="registrado">Con ficha</option><option value="bonus">Bonus sin ficha</option></select></label><button type="reset" class="icon-button" aria-label="Restablecer filtros" title="Restablecer filtros">${icon('rotate-ccw')}</button></form><div class="collection-meta"><p id="result-count" aria-live="polite">53 objetos · 51 registros y 2 bonus</p><div><a href="data/collection.json" download>${icon('download')} Datos</a><a href="archivo.html#metodo">Método</a></div></div><div class="object-grid" id="object-grid">${records.map(recordCard).join('')}${bonus.map(bonusCard).join('')}</div><div id="empty-results" class="empty-results" hidden><h2>No aparece en el registro.</h2><p>Prueba otra palabra o restablece los filtros. La ausencia de un resultado no demuestra la ausencia de un objeto.</p><button type="button" data-reset>Restablecer filtros</button></div></div></section>
<section class="content-wide object-story" id="historia">${intro('Del uso al archivo','Una carta que se puede ver, pero no leer.','Karla cubrió el texto de su carta antes de registrarla. Esa decisión hace visible un límite: conservar una memoria no equivale a volverla pública.')}<div class="object-story-grid"><figure><img src="img/karla-torres-04.jpg" alt="Carta a mi misma, de Karla Torres: el cuerpo del texto está cubierto por su autora" width="1200" height="718" loading="lazy"><figcaption>Imagen del registro original. Texto cubierto por su autora.</figcaption></figure><ol class="story-stages"><li><b>Escribir</b><p>Una persona de 2026 se dirige a una versión futura de sí misma.</p></li><li><b>Decidir qué mostrar</b><p>El encabezado nombra 2046. Se conserva tal como fue escrito, aunque la apertura del museo sea en 2047.</p></li><li><b>Registrar sin revelar</b><p>La fotografía documenta el soporte y la ocultación. No permite recuperar lo que no se ve.</p></li><li><b>Esperar</b><p>La intimidad del mensaje pertenece a su autora, también cuando llegue la cita.</p></li></ol></div>${refs(['fichas','curso'])}<a class="text-link" href="ficha-02.html#p04">Leer la ficha original de Karla ${icon('arrow-up-right')}</a></section>
<dialog class="record-dialog" id="record-dialog" aria-labelledby="dialog-title"><button type="button" class="icon-button close-dialog" aria-label="Cerrar registro" title="Cerrar registro">${icon('x')}</button><div id="dialog-content"></div></dialog>`;

const archive=`<section class="content-wide archive-intro">${label('Archivo / 03','La confianza también se diseña')}<div class="intro-title"><h1>Lo que sabemos.<br><em>Cómo lo sabemos.</em></h1><p>Las fuentes permiten volver sobre una afirmación. Las omisiones y las correcciones también forman parte de la historia del museo.</p></div><nav class="chapter-nav" aria-label="Secciones del archivo"><a href="#conteo">El conteo</a><a href="#preguntas">Preguntas</a><a href="#metodo">Método</a><a href="#custodia">Custodia</a><a href="#fuentes">Fuentes</a><a href="#historial">Historial</a></nav></section>
<section class="count-section" id="conteo"><div class="content-wide">${intro('01','51 + 2 = 53','El registro visible y el total de la colección se cuentan por separado.')}<div class="count-ledger"><article><b>51</b><h3>Objetos registrados</h3><p>51 fichas, 51 fotografías y 12 autores. Hay registros de conjuntos: no se cuentan sus componentes como nuevas fichas.</p><span class="status-label">Documentado</span></article><article><b>2</b><h3>Objetos bonus</h3><p>Añadidos sin registro. No se inventan autoría, imagen, medidas, material ni ubicación dentro de las cajas.</p><span class="status-label">Testimonio</span></article><article><b>53</b><h3>Objetos en total</h3><p>51 + 2. El resultado incorpora la corrección del responsable del proyecto y sustituye el total anterior.</p><span class="status-label">Calculado desde fuentes declaradas</span></article></div><blockquote class="source-statement">${facts.countSource}</blockquote><p>Esta confirmación resuelve el total. No sustituye un manifiesto por caja ni una inspección del contenido.</p></div></section>
<section class="content-wide questions-section" id="preguntas">${intro('02','Preguntas al archivo','Respuestas editoriales con sus fuentes. La búsqueda usa los textos públicos; no genera recuerdos ni completa datos ausentes.')}<form class="question-search" role="search"><label class="sr-only" for="question-query">Buscar una pregunta</label>${icon('search')}<input type="search" id="question-query" placeholder="Voyager, permiso, fechas, cartas…" autocomplete="off"></form><p id="question-count" class="source-note" aria-live="polite">${questions.length} respuestas documentadas</p><div class="question-list">${questions.map((q,i)=>`<details data-question="${i}"><summary>${q.q}${icon('plus')}</summary><p>${q.answer}</p>${refs(q.sources)}</details>`).join('')}</div><p id="question-empty" hidden>No hay una respuesta editorial para esa consulta. <a href="coleccion.html">Buscar en los registros originales</a>.</p></section>
<section class="method-section" id="metodo"><div class="content-wide">${intro('03','Un archivo con límites visibles','Cada forma de conocimiento necesita una forma distinta de leerse.')}<dl class="status-list">${statuses.map(([name,meaning],i)=>`<div><dt><span class="evidence-symbol e-${i}" aria-hidden="true"></span>${name}</dt><dd>${meaning}</dd></div>`).join('')}</dl><div class="method-notes"><article><h3>La voz de cada ficha</h3><p>Se preservan los títulos, las descripciones y los cinco campos publicados, incluso sus discrepancias. Por ejemplo, el boleto del Biomuseo de Karla dice «cartoncillo» en la descripción y «Plastico» en material. Una nota no debe convertirse en una corrección silenciosa.</p><p>La búsqueda normaliza mayúsculas y acentos y consulta autor, título, descripción, origen y material. No infiere categorías sentimentales ni convierte fechas de compra en fechas de fabricación.</p></article><article><h3>Fuera del archivo público</h3><p>Correos personales, direcciones del propietario, valoraciones monetarias y mensajes reservados. Los dos bonus se cuentan sin completar su información. La ubicación por caja y el inventario detallado del cierre figuran como desconocidos.</p><p>No existe un chat generativo activo ni se envían consultas a un proveedor de IA. Un futuro asistente requerirá citas comprobables, protección de los datos privados y una configuración de servidor independiente.</p></article><article><h3>Imágenes y reconstrucciones</h3><p>Los diagramas web son conceptuales y no están a escala. Las imágenes de objetos provienen de las fichas existentes; la imagen de Isthmus es un dibujo del edificio. Las láminas generadas con IA son borradores de la conversación, conservados con sus limitaciones.</p><p>Una reconstrucción generativa de una memoria requeriría consentimiento y un registro de su testimonio, modelo, instrucciones y revisiones. No se produce ni publica aquí sin esos elementos.</p></article><article><h3>Qué añadió esta edición</h3><p>El atlas de relaciones, la corrección del conteo, la búsqueda y estas notas de procedencia son una ampliación editorial de septiembre de 2026. La referencia a <em>Full Disclosure</em> de MoMA corresponde a esta ampliación; no se atribuye al trimestre original.</p><p>Los enlaces expresan relaciones curatoriales. Una coincidencia de fecha o tema no demuestra influencia ni causalidad.</p></article></div></div></section>
<section class="content-wide custody-section" id="custodia">${intro('04','Cuidar una ausencia durante 21 años','Del taller a una apertura que todavía debe suceder. El estado de cada paso se declara, no se supone.')}<ol class="custody-route">${custody.map((c,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span><div><p class="section-label">${c.status}</p><h3>${c.title}</h3><p>${c.text}</p>${refs([c.source])}</div></li>`).join('')}</ol><div class="custody-open"><h3>Decisiones que aún necesitan responsables</h3><p>Sucesión de custodia; permiso de apertura; qué hacer si Isthmus se traslada o el edificio cambia de uso; consentimiento para publicar después de 2047; continuidad del dominio y copias fuera de línea.</p><a class="text-link" href="archive/condition-report-template.json" download>${icon('download')} Plantilla de parte de conservación</a><p class="source-note">Plantilla vacía, no una inspección realizada. Publicar una nueva acta requiere evidencia y una persona responsable.</p></div></section>
<section class="sources-section" id="fuentes"><div class="content-wide">${intro('05','Volver a las fuentes','Referencias del proyecto, históricas y curatoriales.')}<ol class="source-list">${sources.map((s,i)=>`<li id="source-${s.id}"><span>${String(i+1).padStart(2,'0')}</span><div><p class="section-label">${s.type}</p><h3><a href="${s.url}">${s.title} ${icon('arrow-up-right')}</a></h3><p>${s.note}</p></div></li>`).join('')}</ol></div></section>
<section class="content-wide history-section" id="historial">${intro('06','Corregir sin borrar','Las versiones anteriores se conservan como historia editorial; las afirmaciones vigentes se corrigen donde se leen.')}<ol class="correction-list">${corrections.map(([date,title,body])=>`<li><time>${date}</time><div><h3>${title}</h3><p>${body}</p></div></li>`).join('')}</ol><div class="downloads"><a href="archive/mufu-2026-original.zip" download>${icon('archive')} Sitio original · 4 septiembre 2026</a><a href="archive/original-manifest.json" download>${icon('fingerprint')} Huellas SHA-256 del original</a><a href="data/collection.json" download>${icon('download')} Datos públicos de la colección</a><a href="archive/mufu-2026-expanded.zip" download>${icon('folder-down')} Esta edición · copia fuera de línea</a></div><p class="source-note">El original conserva los errores corregidos en esta edición. Las huellas detectan cambios de archivo; no certifican que una afirmación sea verdadera. Las copias HTML pueden leerse sin conexión; las interacciones funcionan con un servidor estático local.</p><details class="text-alternative"><summary>Láminas generadas durante la conversación ${icon('plus')}</summary><p>Dos borradores generados con IA. La primera imagen aproxima una secuencia semanal que no está documentada. La segunda simplifica las relaciones ópticas y la precisión temporal. Para citar o imprimir, usar la <a href="infografia.html">infografía web corregida</a>.</p><div class="poster-grid"><figure><a href="medios/infografia-trimestre-borrador.png"><img src="medios/infografia-trimestre-borrador.png" alt="Borrador generado con IA: diez semanas para construir un museo; calendario ilustrativo no documentado" width="1122" height="1402" loading="lazy"></a><figcaption>Borrador IA · secuencia ilustrativa</figcaption></figure><figure><a href="medios/infografia-conexiones-borrador.png"><img src="medios/infografia-conexiones-borrador.png" alt="Borrador generado con IA: mapa de conexiones MUFU; ver la versión web corregida" width="1122" height="1402" loading="lazy"></a><figcaption>Borrador IA · conexiones conceptuales</figcaption></figure></div></details></section>`;

fs.writeFileSync('atlas.html',shell('El hilo que une todo','atlas.html','atlas',atlas));
fs.writeFileSync('coleccion.html',shell('53 objetos, 51 rastros visibles','coleccion.html','collection',collection));
fs.writeFileSync('archivo.html',shell('Lo que sabemos','archivo.html','archive',archive));
const archivePage=load(fs.readFileSync('archivo.html','utf8'));
archivePage('.archive-intro .chapter-nav').append('<a href="infografias.html">Infografías</a>');
archivePage('.history-section .source-note').after(`<aside class="visuals-callout"><div><p class="section-label">Láminas visuales</p><h3>Las infografías, a la vista.</h3><p>Dos mapas visuales de MUFU se pueden abrir y descargar a tamaño completo.</p></div><a class="visuals-callout-action" href="infografias.html">Ver las infografías ${icon('arrow-up-right')}</a></aside>`);
fs.writeFileSync('archivo.html',archivePage.html());
const printable=`<section class="content-wide infographic"><div class="print-actions"><a href="atlas.html">${icon('arrow-left')} Volver al atlas</a><button data-print type="button">${icon('printer')} Imprimir</button></div>${label('MUFU · Museo del Futuro','Infografía / cohorte 2026')}<h1>Diez semanas.<br>Un hilo que une todo.</h1><p class="infographic-numbers">10 semanas · 8 módulos · 12 estudiantes · 2 futuros · 53 objetos</p><div class="print-modules">${modules.map(m=>`<article><span>${m.id} ${icon(m.icon)}</span><h2>${m.title}</h2><p>${m.teacher}</p><strong>${m.lesson}</strong><p>${m.from} → ${m.to}</p></article>`).join('')}</div><p>Secuencia de módulos; no equivale a un calendario semanal.</p><div class="print-threads">${threads.map(t=>`<article><h2>${t.name}</h2><h3>${t.question}</h3><p>${t.detail}</p></article>`).join('')}</div><div class="print-equations"><p><b>1977 → 2047</b>70 años · Voyager 1 → cita MUFU<br>5 septiembre · 07:56 Panamá</p><p><b>2005 → 2026 → 2047</b>21 años hacia atrás y hacia adelante<br>Simetría nominal entre años</p><p><b>51 + 2 = 53</b>Objetos registrados + bonus sin ficha<br>Confirmación del responsable</p></div><h2>Las relaciones que atraviesan el curso</h2><ol class="print-edges">${edges.map(([a,b,t,why])=>`<li><b>${nodes.find(n=>n.id===a).title} → ${nodes.find(n=>n.id===b).title}</b><p>${why}</p></li>`).join('')}</ol><p class="print-thesis">Un objeto empieza a significar cuando deja de servir.</p><p>Diagrama conceptual. Pepper es reflexión óptica; Leia es holografía de ficción. Los mundos de 2046 son escenarios especulativos. La apertura física aún debe documentarse.</p>${refs(['curso','conteo','nasa','leia','pepper','disco'])}</section>`;
fs.writeFileSync('infografia.html',shell('Infografía del trimestre','infografia.html','print',printable));
const visuals=`<section class="content-wide visuals-intro">${label('MUFU / 04','Infografías visuales')}<div class="intro-title"><h1>Ver el museo.<br><em>De un vistazo.</em></h1><p>Dos láminas para mirar, compartir o guardar: el recorrido de diez semanas y el mapa que une memoria, representación, poder y tiempo.</p></div><nav class="chapter-nav" aria-label="Infografías disponibles"><a href="#trimestre">El trimestre</a><a href="#conexiones">El hilo que une todo</a><a href="infografia.html">Versión web accesible</a></nav></section>
<section class="visual-poster-section" id="trimestre"><div class="content-wide visual-poster"><div class="visual-poster-copy"><p class="section-label">Lámina 01 / el recorrido</p><h2>Diez semanas<br>para construir un museo.</h2><p>Selección, curaduría, relato, futuros, cápsula y aparición. La lámina reúne los ocho módulos, las 12 personas y el conteo actualizado de 53 objetos.</p><p class="visual-note">Mapa conceptual. La asignación de semanas es una lectura visual, no un calendario documentado de cada módulo.</p><div class="visual-actions"><a href="medios/infografia-trimestre-borrador.png" target="_blank" rel="noopener">${icon('maximize-2')} Abrir a tamaño completo</a><a href="medios/infografia-trimestre-borrador.png" download>${icon('download')} Descargar PNG</a></div></div><figure><a href="medios/infografia-trimestre-borrador.png" target="_blank" rel="noopener"><img src="medios/infografia-trimestre-borrador.png" alt="Infografía visual del trimestre MUFU: diez semanas, ocho módulos, 12 estudiantes y 53 objetos" width="1122" height="1402" fetchpriority="high"></a><figcaption>Infografía visual · trimestre MUFU</figcaption></figure></div></section>
<section class="visual-poster-section visual-poster-section-alt" id="conexiones"><div class="content-wide visual-poster visual-poster-reverse"><figure><a href="medios/infografia-conexiones-borrador.png" target="_blank" rel="noopener"><img src="medios/infografia-conexiones-borrador.png" alt="Mapa visual de conexiones MUFU: Pepper, Star Wars, Voyager, 2005, 2026, 2046 y 2047" width="1122" height="1402" loading="eager"></a><figcaption>Infografía visual · conexiones MUFU</figcaption></figure><div class="visual-poster-copy"><p class="section-label">Lámina 02 / el hilo</p><h2>El hilo que<br>une todo.</h2><p>Un mapa de las conexiones entre Pepper, el mensaje de Leia, Voyager, la cápsula, los futuros de 2046 y la cita de 2047.</p><p class="visual-note">Mapa conceptual. Para consultar fuentes, precisión temporal y relaciones completas, ir al atlas interactivo.</p><div class="visual-actions"><a href="medios/infografia-conexiones-borrador.png" target="_blank" rel="noopener">${icon('maximize-2')} Abrir a tamaño completo</a><a href="medios/infografia-conexiones-borrador.png" download>${icon('download')} Descargar PNG</a><a href="atlas.html">${icon('network')} Explorar el atlas</a></div></div></div></section>
<section class="content-wide visuals-ending"><p>También existe una <a href="infografia.html">versión web accesible e imprimible</a>, con las relaciones completas, fuentes y notas de evidencia.</p></section>`;
fs.writeFileSync('infografias.html',shell('Infografías visuales','infografias.html','visuals',visuals));

const home=load(fs.readFileSync('index.html','utf8').trimEnd());
const homeStatus=home('.estatus').first().remove();
home('#home-atlas').remove();
if(!home('#museum-origin').length){
  const paragraphs=home('.hero .tesis').toArray().map(el=>home.html(el)).join('');
  const scene=home.html(home('.hero .escena'));
  home('#portada').after(`<section id="museum-origin" class="museum-origin wrap"><div><p class="section-label">El museo / Cohorte 2026</p><h2>¿Qué es un museo?</h2>${paragraphs}</div>${scene}</section>`);
}
home('#portada').removeClass('wrap').addClass('museum-hero').html(`<div class="hero-media"><video id="hero-film" muted playsinline loop preload="none" poster="medios/aparicion.jpg" aria-label="Video original de las doce apariciones; reproducción sin sonido"><source src="medios/aparicion.mp4" type="video/mp4"></video></div><div class="hero-overlay wrap"><p class="eyebrow">Isthmus · Panamá · Cohorte 2026</p><h1 class="display h-xl">MUFU<span class="l2">Museo del Futuro</span></h1><p class="hero-deck">53 objetos. Una pared.<br>Una cita en 2047.</p><a class="entrar" href="atlas.html">Entrar al atlas ${icon('arrow-up-right')}</a><a class="hero-read" href="infografias.html">Ver infografías</a><a class="hero-read" href="coleccion.html">Ver la colección</a></div><div class="hero-caption"><span>Última función · video del archivo · 12 apariciones</span><button type="button" id="hero-play" aria-pressed="false" aria-label="Reproducir las apariciones" title="Reproducir las apariciones">${icon('play')}</button><a href="#obra">Ver el registro completo ${icon('arrow-up-right')}</a></div>`);
home('#museum-origin .tesis').last().text('Empezaron con la galería de fotos de su teléfono. Terminaron emparedando sus objetos bajo una escalera, con una cita de apertura prevista para 2047. La placa seguía pendiente en el último registro.');
home('.hero-media').html('<img src="medios/mufuhero.png" width="1672" height="940" fetchpriority="high" alt="Una figura suspendida en una vitrina de vidrio bajo una escalera, frente a la bahía de Panamá.">');
home('#hero-play').remove();
home('.hero-caption>span').text('MUFU · Imagen conceptual');
home('.hero-caption>span').after(homeStatus);
home('script:not([type])').each((_,el)=>{
  let js=home(el).html();
  js=js.replace('fichas de registro · 51 registros','autores · 51 registros');
  js=js.replace(/const APERTURA = new Date\([^;]+;\s*\/\* Fecha del entierro:[\s\S]*?const ENTIERRO = new Date\([^;]+;/,'// Calendar configuration is generated from data/editorial.mjs into assets/facts.js.');
  home(el).html(js);
});
home('script[src="assets/hero.js"]').remove();
const homeAtlas=`<section id="home-atlas" class="home-atlas"><div class="wrap"><div class="home-atlas-head"><p class="section-label">Un museo empieza por una selección</p><a href="coleccion.html">53 objetos ${icon('arrow-up-right')}</a></div><div class="contact-strip">${records.slice(0,13).map(r=>`<a href="${r.source}" title="${esc(r.title)}"><img src="${r.image.src}" alt="${esc(r.title)}" loading="lazy" width="${r.image.width}" height="${r.image.height}"></a>`).join('')}<a class="contact-bonus" href="archivo.html#conteo" aria-label="Dos objetos bonus sin registro">+2<span>sin ficha</span></a></div><div class="home-atlas-copy"><h2>Diez semanas.<br><em>Todo estaba conectado.</em></h2><p>El mensaje de Leia, el Disco de Oro, el fantasma de Pepper y las cartas de una clase. Cuatro hilos para recorrer lo que aprendimos: memoria, representación, poder y tiempo.</p><a href="atlas.html" class="atlas-entry">Explorar el atlas ${icon('arrow-up-right')}</a></div><div class="home-thread-links">${threads.map(t=>`<a href="atlas.html?hilo=${t.id}"><i style="background:${t.color}" aria-hidden="true"></i>${t.name}<span>${t.question}</span>${icon('arrow-up-right')}</a>`).join('')}</div></div></section>`;
home('#cuenta').before(homeAtlas);
home('#home-atlas').after(home('#museum-origin'));
home('#conteo').text('12 autores · 51 registros + 2 bonus = 53 objetos');
home('#recorrido .mom').each((i,el)=>home(el).attr('id',`modulo-original-${String(i).padStart(2,'0')}`));
fs.writeFileSync('index.html',home.html());

const printPage=load(fs.readFileSync('infografia.html','utf8'));
printPage('.print-actions').append(`<a href="medios/mufu-infografia.png" download>${icon('download')} Descargar infografía</a>`);
printPage('.print-threads article').each((i,el)=>printPage(el).attr('style',`border-top:3px solid ${threads[i].color};padding-top:1rem`));
fs.writeFileSync('infografia.html',printPage.html());

const data={facts,people,records,bonus,sources,threads,nodes,edges,questions,sharedTrimester,contributors,learningConnections};
fs.writeFileSync('data/collection.json',JSON.stringify(data,null,2)+'\n');
fs.writeFileSync('assets/data.js',`export default ${JSON.stringify(data).replace(/</g,'\\u003c')};\n`);
fs.writeFileSync('assets/facts.js',`export default ${JSON.stringify(facts)};\n`);
fs.writeFileSync('archive/condition-report-template.json',JSON.stringify({kind:'blank-template',date:null,responsible:null,wallCondition:null,plateInstalled:null,platePhoto:null,domainReviewed:null,offlineCopiesVerified:[],evidence:[],notes:null,physicalOpeningConfirmed:false},null,2)+'\n');
const paths=['index.html','atlas.html','infografias.html','coleccion.html','archivo.html','infografia.html',...people.map(p=>p.url)];
for(const page of [...paths,'404.html','ficha.html']){
  const $=load(fs.readFileSync(page,'utf8').trimEnd());
  $('link').filter((_,el)=>/fonts\.(googleapis|gstatic)\.com/.test($(el).attr('href')||'')).remove();
  applySharedLearning($,page,icon);
  visualEdition($,page,icon);
  fs.writeFileSync(page,$.html().replace(/[ \t]+$/gm,'').trimEnd()+'\n');
}
fs.writeFileSync('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`\n  <url><loc>https://mufu.today/${p==='index.html'?'':p}</loc><lastmod>${facts.revision}</lastmod></url>`).join('')}\n</urlset>\n`);
fs.writeFileSync('llms.txt',`# MUFU · Museo del Futuro\n\nMuseo creado durante diez semanas por 12 estudiantes de Isthmus, Panamá, en 2026.\n\n## Hechos y procedencia\n- 51 objetos declarados y registrados, más dos bonus sin ficha: 53 objetos. Total corregido por Luis Miguel Caamaño el 9 de septiembre de 2026. No son 48.\n- Dos cajas, emparedadas bajo la escalera posterior del edificio 106, Ciudad del Saber. No hay un manifiesto público por caja.\n- Cierre registrado: 4 de septiembre de 2026; hora desconocida.\n- Apertura prevista: 5 de septiembre de 2047 a las 07:56, Panamá (UTC-5). Llegar a la fecha no acredita una apertura física.\n- La fecha coincide con el 70 aniversario de Voyager 1 con precisión de minuto; NASA precisa 12:56:01 UT para el lanzamiento.\n- El relato del proyecto describe una placa de latón pendiente; no hay una actualización física verificada.\n- Cuatro intenciones de selección en la consigna: dar, recuperar, representar el presente y escribir una carta. No son cuatro objetos uniformes por persona.\n\n## El trimestre\n${modules.map(m=>`- ${m.id}: ${m.title} (${m.teacher}). ${m.lesson}`).join('\n')}\n\n## Interpretaciones\nDos escenarios ficticios de Panamá en 2046: transformación (LNS) y colapso (Nodos de Memoria). No son hechos actuales ni pronósticos científicos. Ambos imaginan originales inaccesibles y reconstrucciones visibles. El atlas propone conexiones curatoriales entre memoria, representación, poder y tiempo; no afirma causalidad entre Star Wars, Voyager y Pepper. Pepper es una ilusión por reflexión, no holografía.\n\n## Archivo\n- https://mufu.today/atlas.html\n- https://mufu.today/coleccion.html\n- https://mufu.today/archivo.html\n- https://mufu.today/data/collection.json\n\n51 fotografías y textos de registro conservados; dos bonus sin datos inventados. Correos, domicilios, valoraciones y mensajes reservados quedan fuera. No inferir el contenido de las cartas, categorías de objetos ni pertenencia a cajas. Las fuentes originales y las correcciones se consultan en archivo.html.\n`);
fs.writeFileSync('llms.txt',fs.readFileSync('llms.txt','utf8').replace('https://mufu.today/atlas.html\n- https://mufu.today/coleccion.html','https://mufu.today/atlas.html\n- https://mufu.today/infografias.html\n- https://mufu.today/coleccion.html'));
console.log(`Built ${paths.length} pages; ${records.length} original records + ${bonus.length} bonus; ${edges.length} connections.`);
fs.appendFileSync('llms.txt',`\n## El trimestre compartido\n${sharedTrimester.statement}\n${sharedTrimester.confirmation}\n${sharedTrimester.note}\nMapa de los cruces: https://mufu.today/atlas.html#trimestre-compartido\n`);
fs.appendFileSync('llms.txt',`\n${sharedTrimester.focus}\n${sharedTrimester.siteCredit}\n`);
